[package]
name = "serve"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
http = "*"
http-body = "*"
hyper = "*"
hyperlocal = "*"
log = "*"
tower = "0.4"
tokio = { version = "*", features = ["full"] }

[dev-dependencies]
# TODO(johnny): Remove me. It's used for a couple of unit tests only
# but brings in a lot of dependencies. Replace with a hyper server?
warp = "0.3"
tempfile = "*"
