[package]
name = "parser"
version = "0.1.0"
authors = ["Estaury <info@estuary.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "flow-parser"
path = "src/main.rs"


[dependencies]
json = { path = "../json", version = "0.0.0" }
doc = { path = "../doc", version = "0.0.0" }

avro-rs = { version = "*", features = ["snappy"] }
base64 = "*"
bytes = "*"
caseless = "*"
chardetng = "*"
chrono = "*"
csv = "*"
encoding_rs = {version = "*", features = ["serde"]}
flate2 = "*"
mime = "*"
num-bigint = "*"
schemars = "*"
serde = {version = "*", features=["derive"]}
serde_json = {version = "*", features = ["raw_value"]}
structopt = "*"
tempfile = "*"
thiserror = "*"
tracing = "*"
tracing-subscriber = {version = "*", features = ["time", "json", "env-filter"]}
unicode-bom = "*"
unicode-normalization = "*"
url = "*"
uuid = {version = "*", features = ["v4"]}
zip = "*"
strum = { version = "0.24.1", features = ["derive"] }
bytecount = { version = "0.6.3", features = ["runtime-dispatch-simd"] }
lazy_static = "1.4.0"
regex = "1.5.6"

[dev-dependencies]
assert_cmd = "*"
tempdir = "*"
insta = "*"
