[package]
name = "schemalate"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "flow-schemalate"
path = "src/main.rs"

[dependencies]
doc = { path = "../doc" }
flow_cli_common = { path = "../flow_cli_common" }
json = { path = "../json" }
proto-flow = { path = "../proto-flow" }

anyhow = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
prost = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
