[package]
name = "flow_cli_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
clap = {version = "*", features = ["derive"]}
atty = "*"
tracing = "*"
tracing-subscriber = {version = "*", features = ["json", "env-filter", "fmt", "time"]}
