[build]
rustflags = ["-D", "warnings"]

# This just provides a default value for FLOW_VERSION during development, so that you can compile
# without this being set. If FLOW_VERSION is defined, then this has no effect.
[env]
FLOW_VERSION = "dev"
# Provide a default DATABASE_URL which is used if none others are set.
# This is the database presented by a local `supabase start`.
DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/postgres"
