[package]
name = "sqltest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sqlx = { version = "*", features = [ "postgres", "runtime-tokio-rustls" ] }
tokio = { version = "1", features = ["full"] }