[package]
name = "json"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
addr = { workspace = true }
bigdecimal = { workspace = true }
bitvec = { workspace = true }
regex = { workspace = true }
fxhash = { workspace = true }
iri-string = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
glob = { workspace = true }

[[bench]]
name = "github_events"
harness = false

[[bench]]
name = "citi_rides"
harness = false
