[package]
name = "journal-client"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2021"

[dependencies]
assemble = {path = "../assemble"}
bytes = "*"
proto-gazette = { path = "../proto-gazette" }
proto-grpc = { path = "../proto-grpc", features = ["broker_client"] }

lazy_static = "*"
thiserror = "*"
futures-core = "*"
reqwest = {version = "*", features = ["stream"]}
tonic = {version = "*", features = [ "tls", "tls-roots"]}
tokio = {version = "*", features = ["rt", "net", "macros"]}
tracing = "0.1"
tower = "0.4"
serde = "*"
async-compression = { version = "0.3.14", features = ["all-algorithms", "tokio", "futures-io"] }
#pin-project = "1.0.12"
futures = "0.3.24"
uuid = { version = "1.1.2", features = ["serde"] }
pin-project = "1.0.12"
exponential-backoff = "1.1.0"
#tokio-util = { version = "0.7.4", features = ["compat", "tracing"] }

