[package]
name = "connector_proxy"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "flow-connector-proxy"
path = "src/main.rs"

[dependencies]
doc = { path = "../doc", version = "0.0.0" }
flow_cli_common = { path = "../flow_cli_common" }
network-proxy = { path = "../network-proxy", version = "0.1.0" }
protocol = { path = "../protocol", version = "0.0.0" }

async-trait="*"
async-stream="*"
bytes = "*"
byteorder="*"
clap = { version = "^3", features = ["derive"] }
futures-core = "*"
futures-util="*"
futures="*"
json-pointer="*"
libc="*"
prost = "*"
schemars = "*"
serde = { version = "*", features = ["derive"]}
serde_json = { version = "*", features = ["raw_value"]}
structopt = "*"
strum = "*"
strum_macros = "*"
tempfile="*"
thiserror = "*"
tokio = { version = "1.15.0", features = ["full"] }
tokio-util = { version = "*", features = ["io"] }
tracing="*"
validator = { version = "*", features = ["derive"] }