[package]
name = "control"
version = "0.1.0"
edition = "2021"
default-run = "control"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flow_cli_common = { path = "../flow_cli_common" }

anyhow = "1.0.52"
async-trait = "0.1.52"
axum = { version = "0.4.6", features = ["headers"] }
axum-macros = "0.1.1"
base64 = "0.13.0"
caseless = "*"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.0.13", features = ["derive"] }
config = "0.11.0"
futures = "0.3.19"
hmac = "0.12.1"
hyper = { version = "0.14.16", features = ["full"] }
once_cell = "1.9.0"
rand = "0.8.4"
reqwest = { version = "0.11.9", features = ["json"] }
rusqlite = { version = "*", features = ["bundled-full"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = { version = "1.0.74", features = ["raw_value"] }
serde_with = { version = "1.11.0", features = ["base64", "chrono"] }
sha2 = "0.10.2"
sqlx = { version = "0.5.11", features = [ "chrono", "postgres", "runtime-tokio-rustls" ] }
strum = { version = "0.24.0", features = ["derive"] }
tempfile = "3.3.0"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["full"] }
tower = { version = "0.4.11", features = ["limit"] }
tower-http = { version = "0.2.2", features = ["cors", "trace"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
unicode-normalization = "*"
url = {version = "2.2.2", features = ["serde"]}
validator = {version = "*", features = ["derive"]}
heck = "0.4.0"

[dev-dependencies]
ctor = "0.1.21"
insta = { version = "1.10.0", features = ["redactions"] }
mime = "0.3.16"

[features]
flowctl = []
postgres = []
default = []

[[test]]
name = "it"
required-features = ["flowctl", "postgres"]
