[package]
name = "tuple"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

authors = [
"Benjamin Fry <benjaminfry@me.com>",
"Vincent Rouill√© <vincent@clikengo.com>",
"Estuary Technologies, Inc <johnny@estuary.dev>",
]
license = "MIT OR Apache-2.0"

description = """
Portions of the `tuple` module, extracted from:
High level client bindings for FoundationDB.

This subdirectory / crate is licensed under the terms of the original
work (MIT or Apache 2), which is available at:
  https://github.com/Clikengo/foundationdb-rs
"""

[dependencies]
memchr = { workspace = true }
serde_json = { workspace = true }

[features]
num-bigint = []
uuid = []