[package]
name = "network-tunnel"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "flow-network-tunnel"
path = "src/main.rs"

[dependencies]
flow_cli_common = { path = "../flow_cli_common" }
async-process = { path = "../async-process" }

async-trait={ workspace = true }
base64={ workspace = true }
futures={ workspace = true }
rand = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }